# -*- coding: utf-8 -*-
"""GESTÃO DE DADOS - Introducao-ao-EDA-v3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AsCD5-3MAfzgyn5WU9m5YBJYXyMIeVn3
"""

import requests
import pandas as pd
import json
import seaborn as sns
from matplotlib import pyplot as plt
from textwrap import wrap

"""## Introdução ao EDA (Exploratory Data Analysis)

Sempre que deparamos com um desafio envolvendo dados, temos o dever de entender melhor esses dados que estamos transformando.

Uma das formas mais utilizadas para entender os nossos dados é o **Processo de EDA (Exploratory Data Analysis ou Análise Exploratória de Dados)**

Muitas vezes não sabemos como fazer a extração de informações e também quais objetivos sobre essa base. Uma situação exemplo é quando um cientista de dados que trabalhou anos em uma empresa do ramo de Telecomunicações, após uma recolocação de mercado está atualmente alocado em uma empresa da área de Educação. Cientistas de dados devem estar preparados para transformar dados de qualquer natureza.

O EDA consiste em um processo genérico para obtenção de informações e Conclusões em bases de dados, como meio nesse processo utilizamos ferramentas de Estatística, Representações Gráficas e Modelos Matemáticos para extração dessas informações. O processo pode ser dividido em 6 Etapas:

1. **Coleta e Dominância do Conhecimento**: Obter os dados requeridos e dominar conhecimentos relacionados ao conhecimento dos dados

2. **Análise Descritiva**: Entender a estrutura e natureza dos dados, obtendo uma visão completa das características da base de dados.

3. **Consolidação dos Dados**: Modificar a estrutura e natureza dos dados conforme os objetivos estabelecidos.

3. **Análise sob a Teoria Distribuição Normal**: Entender o comportamento dos dados conforme a teoria da Distribuição Normal.

4. **Tratamento de Valores Nulos e Valores Atípicos**: A ausência de dados e valores fora da realidade conforme a Teoria Distribuição Normal  contaminam as informações geradas a partir da base analisada, portanto, esses valores devem ser mitigados ou removidos.

5. **Visualização de Dados**: A representação gráfica dos dados analisados é uma maneira eficiente de gerar informações.

6. **Extração de Padrões**: Usando algoritmos podemos verificar padrões escondidos que gráficos ou Estatística básica não alcançam, modelos de machine learning podem ser utilizados para entendimento da base analisada.

**Não há um consenso sobre um definitivo do processo de EDA, o informado neste documento é um amálgama de várias bibliografias.**

Você sabe quanto e com o que o senadores gastaram com as verbas de Cotas para Exercício da Atividade Parlamentar dos Senadores (CEAPS)?

CEAPS são gastos pertinentes à atividade parlamentar do senador ao longo do seu mandato, esses gastos são ressarcidos pela união.

será que nossos representantes no senado fazem o uso consciente desses recursos?

Vamos explorar a base desses gastos e prover resultados quali-quantitativos para determinar se há uma boa gestão.

Dados Abertos referentes ao Senado Federal estão presentes no site https://www12.senado.leg.br/transparencia

## Coleta e Dominância do Conhecimento
"""

response = requests.get('https://adm.senado.gov.br/adm-dadosabertos/api/v1/senadores/despesas_ceaps/2018/').content

data = json.loads(response)

"""data;"""

df = pd.json_normalize(data)

df

# Realizar consumo dos dados via api de forma automatizada de 2015 à 2022.

datas = [2015,2016,2017,2018,2019,2020,2021,2022]

for x in datas:
    response = requests.get('https://adm.senado.gov.br/adm-dadosabertos/api/v1/senadores/despesas_ceaps/{}/'.format(x)).content

    if x == min(datas):
        data = json.loads(response)
    else:
        data.extend(json.loads(response))

df = pd.json_normalize(data)

df

df.to_csv('ceaps_senado_2015_2022.csv')

response = requests.get('https://legis.senado.leg.br/dadosabertos/senador/lista/legislatura/54/56.json').content

data = json.loads(response)

data['ListaParlamentarLegislatura']['Parlamentares']['Parlamentar'];

data = data['ListaParlamentarLegislatura']['Parlamentares']['Parlamentar']

df_senadores = pd.json_normalize(data)

df_senadores

df_senadores.to_csv('senadores_2015_2022.csv')

df_senadores = pd.read_csv('senadores_2015_2022.csv')

df = pd.read_csv('ceaps_senado_2015_2022.csv')

"""## Analise Descritiva

#### DF
"""

df.ano.min()

df.ano.max()

df.columns

df.info()

df[['valorReembolsado']].describe()

# Qual é o registro com Valor Minímo da Coluna valorReembolsado?
df[df['valorReembolsado'] == df['valorReembolsado'].min()]

# Qual é o registro com Valor Máximo da Coluna valorReembolsado?
df[df['valorReembolsado'] == df['valorReembolsado'].max()]

"""#### DF_SENADORES"""

df_senadores.columns

df_senadores.info()

df_senadores.head(10)

"""Considerações da Analise Descritiva para próxima etapa de Consolidação dos Dados:

Ações Realizadas:
1. Carga dos Dados via API.
2. União documentos.

Ações Futuras:
1. Coluna Date está em string, transformar para datetime.
2. Existe Números Negativos Na Coluna valorReembolsado, verificar tratativa.
3. Apagar Colunas desnecessárias
4. Ajustar Nome Parlamentar
5. Merge das Tabelas df e df_senadores

## Consolidação dos Dados

#### DF
"""

# Testar se a col data pode ser transformada em datetime
df['data'].astype('datetime64')

"""Vemos que não possivel transformar toda a coluna data em datetime, o erro acusado que existes valores na coluna fora calendário do Pandas."""

# filtro se exite mesmo um registo com esses valores
df[df['data'] == '2915-10-06']

# Podemos transformar os dados em data mitigando os erros com o coerce
# Criamos a coluna data_ para testes
df['data_'] = pd.to_datetime(df['data'], errors = 'coerce')

# Filtro com valores de data com problemas
df[df['data_'].isna()]

# Ajuste as datas com problemas no filtro acima

for index, row in df[df['data_'].isna()].iterrows():
    dia = row['data'][-2:]
    df['data'].iloc[index]  = '{}-{}-{}'.format(row['ano'],row['mes'],dia)

# Teste a tratativa acima transforma a coluna date em datetime
df['data'].astype('datetime64')

# Transformar os dados para datetime
df['data'] = df['data'].astype('datetime64')
# Apagar a coluna de teste
del df['data_']

# Verificar se existe valores negativos na col valorReembolsado
# df[df['valorReembolsado'] <= 0]
df[df['valorReembolsado'] < 0]

# Transforme os valores menores de 0 em Absoluto
df['valorReembolsado'] = abs(df['valorReembolsado'])

"""#### DF_SENADORES"""

# Vamos apagar colunas desnecessárias
del df_senadores['IdentificacaoParlamentar.UrlPaginaParlamentar']
del df_senadores['IdentificacaoParlamentar.EmailParlamentar']
del df_senadores['IdentificacaoParlamentar.UrlPaginaParticular']
del df_senadores['IdentificacaoParlamentar.UrlFotoParlamentar']
del df_senadores['IdentificacaoParlamentar.CodigoPublicoNaLegAtual']
del df_senadores['IdentificacaoParlamentar.FormaTratamento']
del df_senadores['Mandatos.Mandato.Exercicios.Exercicio.SiglaCausaAfastamento']
del df_senadores['IdentificacaoParlamentar.UfParlamentar']
del df_senadores['Mandatos.Mandato.Exercicios.Exercicio.DataLeitura']
del df_senadores['Mandatos.Mandato']
del df_senadores['Mandatos.Mandato.Suplentes.Suplente']
del df_senadores['Mandatos.Mandato.Exercicios.Exercicio']

# Transforme o nome parlamentar em maiuscula
df_senadores['IdentificacaoParlamentar.NomeParlamentar'] = df_senadores['IdentificacaoParlamentar.NomeParlamentar'].apply(lambda x: x.upper())

# Corrija a Tipagem das colunas de natureza data em objeto para datetime
df_senadores['Mandatos.Mandato.Exercicios.Exercicio.DataInicio'] = pd.to_datetime(df_senadores['Mandatos.Mandato.Exercicios.Exercicio.DataInicio'], errors = 'coerce')
df_senadores['Mandatos.Mandato.Exercicios.Exercicio.DataFim'] = pd.to_datetime(df_senadores['Mandatos.Mandato.Exercicios.Exercicio.DataFim'], errors = 'coerce')

df_senadores['Mandatos.Mandato.PrimeiraLegislaturaDoMandato.DataInicio'] = pd.to_datetime(df_senadores['Mandatos.Mandato.PrimeiraLegislaturaDoMandato.DataInicio'], errors = 'coerce')
df_senadores['Mandatos.Mandato.PrimeiraLegislaturaDoMandato.DataFim'] = pd.to_datetime(df_senadores['Mandatos.Mandato.PrimeiraLegislaturaDoMandato.DataFim'], errors = 'coerce')

df_senadores['Mandatos.Mandato.SegundaLegislaturaDoMandato.DataInicio'] = pd.to_datetime(df_senadores['Mandatos.Mandato.SegundaLegislaturaDoMandato.DataInicio'], errors = 'coerce')
df_senadores['Mandatos.Mandato.SegundaLegislaturaDoMandato.DataFim'] = pd.to_datetime(df_senadores['Mandatos.Mandato.SegundaLegislaturaDoMandato.DataFim'], errors = 'coerce')

# Coluna de id para int
df_senadores['IdentificacaoParlamentar.CodigoParlamentar'] = df_senadores['IdentificacaoParlamentar.CodigoParlamentar'].astype(int)

"""#### Merge dos datasets DF e DF_SENADORES

Para fazer uma união entre bases de dados temos que procurar chaves primárias em comum entre as duas bases em questão.

Qual seria essas chaves?
"""

df_senadores.head(5)

df_senadores.columns

df.head(5)

df.tail(5)

"""Analisando as duas bases, podemos integrar elas com as informações de **Nome do Parlamentar** e **Numero Legislatura**.

Já colocamos o **Nome do Parlamentar** de cada base com as mesmas caracteristicas, falta criar uma coluna **Numero Legislatura** na base DF.
"""

# Criação da Coluna Numero Legislatura referente ao gasto na base DF

df['numLegistlatura'] = ''

index_55 = df[(df['data'] >= '2015-02-01') & (df['data'] <= '2019-01-31')].index

index_56 = df[(df['data'] >= '2019-02-01') & (df['data'] <= '2023-01-31')].index

df.loc[index_55,'numLegistlatura'] = '55'

df.loc[index_56,'numLegistlatura'] = '56'

#  Merge entre as bases DF e DF_SENADORES
df_merged = df.merge(df_senadores, left_on=['nomeSenador'],
                       right_on=['IdentificacaoParlamentar.NomeParlamentar'],
                       how = 'left')

df_merged.info()

#  Filtro dos registros de gastos que não teve o merge desejado
df_nan = df_merged[df_merged['IdentificacaoParlamentar.CodigoParlamentar'].isna()]

df_nan['nomeSenador'].unique()

df_nan['valorReembolsado'].sum()

#  prova que existe valores que não estão batendo.
df_senadores[df_senadores['IdentificacaoParlamentar.NomeParlamentar'].isin(df_nan['nomeSenador'].unique())]

df_senadores['IdentificacaoParlamentar.NomeParlamentar'].unique()

# rodar a instalação do pacote apenas uma vez
!pip install unidecode

# Crie uma função que corrija os nomes para um mesmo padrão nas bases DF e DF_senadores

df_senadores.loc[df_senadores['IdentificacaoParlamentar.NomeParlamentar'] == 'JEAN-PAUL PRATES', 'IdentificacaoParlamentar.NomeParlamentar'] = 'JEAN PAUL PRATES'
df_senadores.loc[df_senadores['IdentificacaoParlamentar.NomeParlamentar'] == 'WEVERTON', 'IdentificacaoParlamentar.NomeParlamentar'] = 'WEVERTON ROCHA'
df_senadores.loc[df_senadores['IdentificacaoParlamentar.NomeParlamentar'] == 'MARIA ELIZA', 'IdentificacaoParlamentar.NomeParlamentar'] = 'MARIA ELIZA DE AGUIAR E SILVA'
df_senadores.loc[df_senadores['IdentificacaoParlamentar.NomeParlamentar'] == 'PEDRO CHAVES', 'IdentificacaoParlamentar.NomeParlamentar'] = 'PEDRO CHAVES DOS SANTOS FILHO'
df_senadores.loc[df_senadores['IdentificacaoParlamentar.NomeParlamentar'] == 'DR. SAMUEL ARAUJO', 'IdentificacaoParlamentar.NomeParlamentar'] = 'SAMUEL ARAUJO'

from unidecode import unidecode
df['nomeSenador'] = df['nomeSenador'].apply(unidecode)
df_senadores['IdentificacaoParlamentar.NomeParlamentar'] = df_senadores['IdentificacaoParlamentar.NomeParlamentar'].apply(unidecode)

df_merged = df.merge(df_senadores, left_on=['nomeSenador'],
                       right_on=['IdentificacaoParlamentar.NomeParlamentar'],
                       how = 'left')

df = df_merged

"""Considerações da Analise Descritiva para próxima etapa de Análise sob a Teoria Distribuição Normal:

Ações Realizadas:
1. Coluna Date está em string, transformar para datetime.
2. Existe Números Negativos Na Coluna valorReembolsado, verificar tratativa.
3. Apagar Colunas desnecessárias
4. Ajustar Nome Parlamentar
5. Merge das Tabelas df e df_senadores

Ações Futuras:
1. Verificar valores nulos presentes nas colunas documento e detalhamento
2. Verificar Comportamento da coluna valorReembolsado
3. Valores nulos presentes nas colunas documento e detalhamento não são pertinentes para eliminação ou de inserção de novos valores.

## Análise sob a Teoria Distribuição Normal
"""

sns.histplot(df["valorReembolsado"])

# Como resolver essa visulização acima? vemos a existência de outliers estão "sujando" o histograma.

df_filter = df[df["valorReembolsado"] < df["valorReembolsado"].quantile(.95)]

sns.histplot(df_filter['valorReembolsado'])

# Realize o .describe() desses dados filtrados.
df_filter[['valorReembolsado']].describe()

# Vamos Entender os outliers? Possivelmente são informações importantes para simplemente serem descartadas.
# Realize o .describe() desses dados.

df_outliers = df[df["valorReembolsado"] >= df["valorReembolsado"].quantile(.95)]

df_outliers[['valorReembolsado']].describe()

sns.histplot(df_outliers[['valorReembolsado']])

"""Considerações da Analise Descritiva para próxima etapa de Análise sob a Tratamento de Valores Nulos e Valores Atípicos:

Ações Realizadas:
1. Verificar valores nulos presentes nas colunas documento e detalhamento
2. Verificar Comportamento da coluna valorReembolsado
3. Valores nulos presentes nas colunas documento e detalhamento não são pertinentes para eliminação ou de inserção de novos valores.

Ações Futuras:
1. Validar valores nulos da Col detalhamento
2. Tratativa para Valores Outliers

## Tratamento de Valores Nulos e Valores Atípicos
"""

10000 / df.valorReembolsado.sum()

df[df['detalhamento'].isna()]

# Calcule qual é a % de valores nulos na col detalhamento
len(df[df['detalhamento'].isna()]) / len(df) * 100

"""**é pertinente apagar ou alterar os valores nulos e outliers da base?**

Considerações da Analise Descritiva para próxima etapa de Análise sob a Tratamento de Valores Nulos e Valores Atípicos:

Ações Realizadas:
1. Validar valores nulos da Col detalhamento
2. Tratativa para Valores Outliers

Ações Futuras:
1. Extrair insights por visualização de dados

## Visualização de Dados
"""

# Filtro para Retirar Senadores que exerceram o mandato menos que 1 ano.
cod_senadores_menos_365dias = df_senadores[(~df_senadores['Mandatos.Mandato.Exercicios.Exercicio.DataFim'].isna()) &
                                           (df_senadores['Mandatos.Mandato.DescricaoParticipacao'] != 'Titular') &
                                           ((df_senadores['Mandatos.Mandato.Exercicios.Exercicio.DataFim'] - df_senadores['Mandatos.Mandato.Exercicios.Exercicio.DataInicio'] ).dt.days < 365)
                                          ]['IdentificacaoParlamentar.CodigoParlamentar'].values

df_senadores_mais_365dias = df[~df['IdentificacaoParlamentar.CodigoParlamentar'].isin(cod_senadores_menos_365dias)]

# Vamos ver quem são os 5 senadores mais gastões ou econômicos do senado? Utilize Tabelas para representar os metadados.

group_senador_valorReembolsado = df[['nomeSenador','IdentificacaoParlamentar.CodigoParlamentar','valorReembolsado']].groupby(['nomeSenador','IdentificacaoParlamentar.CodigoParlamentar']).sum(['valorReembolsado']).sort_values(by='valorReembolsado',ascending=False).reset_index()

group_senador_valorReembolsado = group_senador_valorReembolsado[~group_senador_valorReembolsado['IdentificacaoParlamentar.CodigoParlamentar'].isin(cod_senadores_menos_365dias)]

group_senador_valorReembolsado.head(5)

group_senador_valorReembolsado.tail(5)

"""Temos um problema, temos valores baixos pelo fato que normalmente senadores eleitos são substituidos temporariamente por N motivos por seus respectivos suplentes, nesse caso temos que classificar em **senadores titulares** e **senadores suplentes**.

Precisamos melhorar nossa base de dados, portanto, devemos procurar mais dados abertos sobre o mandato dos senadores. Para isso temos que voltar na etapa, fazer carregamento e enriquecimento de dados na primeira etapa.

Consulte as api neste [link](https://legis.senado.leg.br/dadosabertos/docs/resource_ListaSenadorService.html)
"""

# Qual são os 5 partidos Mais Gastões ou econômicos do senado?
# Utilize Tabelas para representar os metadados.

group_partido_valorReembolsado = df_senadores_mais_365dias

group_partido_valorReembolsado = df[['IdentificacaoParlamentar.SiglaPartidoParlamentar','valorReembolsado']].groupby(['IdentificacaoParlamentar.SiglaPartidoParlamentar']).sum(['valorReembolsado']).sort_values(by='valorReembolsado',ascending=False).reset_index()

group_partido_valorReembolsado.head(5)

group_partido_valorReembolsado.tail(5)

# Faça um comparativo entre os mandatos de 2019 - 2022 e 2015 - 2018, qual foi o custo total para ambos mandatos por ano?
# Utilize Gráfico de linha para representar os metadados.

# Qual são os 5 tipos de despesa mais utilizadas por senadores?
# Desfio: Some o restante dos tipos de despesas em uma barra "Outros"?
# Utilize Gráfico de Barra para representar os metadados.

group_despesa_quantidade = df_senadores_mais_365dias

group_despesa_quantidade = group_despesa_quantidade[['id','tipoDespesa']].groupby(['tipoDespesa']).count().sort_values(by='id',ascending=False).reset_index()

group_despesa_quantidade['id'] = group_despesa_quantidade.id * 0.001

group_despesa_quantidade['tipoDespesa'] = group_despesa_quantidade['tipoDespesa'].apply(lambda row: '\n'.join(wrap(row, 30)))

plt.figure(figsize=(10,11))
ax = sns.barplot(data=group_despesa_quantidade, x="id", y="tipoDespesa");
ax.set(xlabel=None, ylabel=None)
ax.set(xticklabels=[])
ax.bar_label(ax.containers[0], fmt='{:.2f} Mil', padding= 5)
ax.set(title='Quatidade de Gastos Reembolsados por Tipo utilizado por Senadores da República entre 2015 e 2022');
sns.despine(left=True, bottom=True)

# Qual são os 5 tipos de despesa mais gastas por senadores?
# Utilize Tabelas para representar os metadados.

group_despesa_valorReembolsado = df_senadores_mais_365dias

group_despesa_valorReembolsado = group_despesa_valorReembolsado[['tipoDespesa','valorReembolsado']].groupby(['tipoDespesa']).sum(['valorReembolsado']).sort_values(by='valorReembolsado',ascending=False).reset_index()

group_despesa_valorReembolsado['valorReembolsado'] = group_despesa_valorReembolsado.valorReembolsado * 0.00001

group_despesa_valorReembolsado['tipoDespesa'] = group_despesa_valorReembolsado['tipoDespesa'].apply(lambda row: '\n'.join(wrap(row, 30)))

plt.figure(figsize=(10,11))
ax = sns.barplot(data=group_despesa_valorReembolsado, x="valorReembolsado", y="tipoDespesa");
ax.set(xlabel=None, ylabel=None)
ax.set(xticklabels=[])
ax.bar_label(ax.containers[0], fmt='{:.2f} Mi', padding= 5)
ax.set(title='Quantia dos Gastos Reembolsados em Reais por Tipo utilizado por Senadores da República entre 2015 e 2022');
sns.despine(left=True, bottom=True)

#group_gasto_valorReembolsado_medio.columns

# Qual é o gasto médio entre Homens e Mulheres?
# Utilize Tabelas para representar os metadados.

group_gasto_valorReembolsado_medio = df_senadores_mais_365dias

group_gasto_valorReembolsado_medio[['IdentificacaoParlamentar.SexoParlamentar','valorReembolsado']].groupby(['IdentificacaoParlamentar.SexoParlamentar']).mean(['valorReembolsado']).sort_values(by='valorReembolsado',ascending=False).reset_index()

group_gasto_valorReembolsado_medio[['IdentificacaoParlamentar.SexoParlamentar','valorReembolsado']].groupby(['IdentificacaoParlamentar.SexoParlamentar']).median(['valorReembolsado']).sort_values(by='valorReembolsado',ascending=False).reset_index()

df_senador_sexo_legislatura = df[['IdentificacaoParlamentar.SexoParlamentar','numLegistlatura','IdentificacaoParlamentar.CodigoParlamentar']]

df_senador_sexo_legislatura['IdentificacaoParlamentar.CodigoParlamentar'].astype(int)

df_senador_sexo_legislatura['numLegistlatura']

str(df_senador_sexo_legislatura['IdentificacaoParlamentar.CodigoParlamentar']) + '-' + df_senador_sexo_legislatura['numLegistlatura']

df_senador_sexo_legislatura['CodigoParlamentar_numLegistlatura'] = str(df_senador_sexo_legislatura['IdentificacaoParlamentar.CodigoParlamentar']) + '-' + df_senador_sexo_legislatura['numLegistlatura']

df_senador_sexo_legislatura['CodigoParlamentar_numLegistlatura']

df_senador_sexo_legislatura['CodigoParlamentar_numLegistlatura'].unique()

# Representividade Feminina aumentou em 2019 - 2022 em comparação a legislatura anteior?
# Utilize Gráfico de pizza para representar os metadados.

df_senador_sexo_legislatura = df[['IdentificacaoParlamentar.SexoParlamentar','numLegistlatura','IdentificacaoParlamentar.CodigoParlamentar']]



df_senadores[['IdentificacaoParlamentar.SexoParlamentar','numLegistlatura','IdentificacaoParlamentar.CodigoParlamentar']].groupby(['IdentificacaoParlamentar.SexoParlamentar','numLegistlatura']).count().reset_index()

""""Se a saúde pública no Brasil parece estar ruim das pernas, isso jamais atingirá senadores, ex-senadores, suplentes que assumiram o cargo, tampouco seus cônjuges e dependentes. E para que isso seja possível, é exigido um único requisito destes políticos: exercício ininterrupto por 180 dias. Isso quer dizer que nenhum deles precisa contribuir para ter direito ao plano de saúde mais cobiçado do país."

[fonte](https://gilbert92.jusbrasil.com.br/artigos/141608410/plano-de-saude-de-senadores-e-vitalicio-completo-e-estendido-a-conjuge-e-dependentes)

com base na afirmação abaixo responda a alternativa abaixo:
"""

# Quais são os Senadores Suplentes exerceram mais de 180 dias de mandato?
# Utilize Tabelas para representar os metadados.

# Existe uma Correlação entre idade do senador e gastos gerados por ele?
# Utilize Gráfico de disperssão para representar os metadados.

"""#### Dever de casa

Integre as bases [profissões](https://legis.senado.leg.br/dadosabertos/docs/resource_ListaSenadorService.html?_gl=1*1m0s91v*_ga*MjEyNTA3MDAxOC4xNjgwNDc3NzU2*_ga_CW3ZH25XMK*MTY4MTUyMTA1Ny40LjEuMTY4MTUyMTMzNi4wLjAuMA..#resource_ListaSenadorService_profissaoSenadorXml_GET) e [historicoAcademico](https://legis.senado.leg.br/dadosabertos/docs/resource_ListaSenadorService.html?_gl=1*1m0s91v*_ga*MjEyNTA3MDAxOC4xNjgwNDc3NzU2*_ga_CW3ZH25XMK*MTY4MTUyMTA1Ny40LjEuMTY4MTUyMTMzNi4wLjAuMA..#resource_ListaSenadorService_historicoAcademicoSenadorXml_GET) no EDA e gere visualizações e insights com esses novos dados.

#### Desafio

Correlacione o período da pandemia do COVID-19 com os gastos de CEAPS. Crie o merge dos dados e novas vizualizações sobre isso.
"""

