# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VAmixE9hGyIn3xZe8wqP0LbZfqAs1ujd
"""

class No:
  def __init__(self,val):
    self.val=val
    self.filhos=[]

def gerarArvore(raiz,nivel):
  if nivel>=2:
    return
  nfilhos=random.randint(0,5)
  for i in range(nfilhos):
    raiz.filhos.append(No(random.randint(0,100)))
    gerarArvore(raiz.filhos[i],nivel+1)

def imprimirPreOrdem(raiz):
  print(raiz.val)
  for filho in raiz.filhos:
    imprimirPreOrdem(filho)

def imprimirPosOrdem(raiz):
  for filho in raiz.filhos:
    imprimirPosOrdem(filho)
  print(raiz.val)


import random
random.seed(51254)
raiz=No(random.randint(0,100))

gerarArvore(raiz,0)
print("pre ordem")
imprimirPreOrdem(raiz)
print("pos ordem")
imprimirPosOrdem(raiz)